version: 2

updates:
  - package-ecosystem: "gradle"
    ignore:
      - dependency-name: "io.github.libxposed:*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "ci(deps)"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      libxposed:
        patterns:
          - "io.github.libxposed*"

  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci(deps)"
    directory: "/"
    schedule:
      interval: "monthly"
